working_dir: &working_dir ~/app
version: 2.1
jobs:
  angular:
    
    docker:
      - image: cimg/python:2.7
    steps:
      - checkout
      - run:
          name: Build angular
          no_output_timeout : 55m
          command: echo Hello, World!;python ox.py
            
      #####################################################
  java:
      
      docker:
        - image: cimg/python:2.7
      steps:
        - checkout
        - run:
            name: Build java
            no_output_timeout : 55m
            command: echo Hello, World!;python ox.py
  python:
    
    docker:
      - image: cimg/python:2.7
    steps:
      - checkout
      - run:
          name: Build python
          no_output_timeout : 55m
          command: echo Hello, World!;python ox.py
      
  vue:
      
      docker:
        - image: cimg/python:2.7
      steps:
        - checkout
        - run:
            name: Build vue
            no_output_timeout : 55m
            command: echo Hello, World!;python ox.py
  node:
    
    docker:
      - image: cimg/python:2.7
    steps:
      - checkout
      - run:
          name: Build node
          no_output_timeout : 55m
          command: echo Hello, World!;python ox.py
  angula:
    
    docker:
      - image: cimg/python:2.7
    steps:
      - checkout
      - run:
          name: Build angular
          no_output_timeout : 55m
          command: echo Hello, World!;python ox.py
            
      ########################################################################
  jav:
      
      docker:
        - image: cimg/python:2.7
      steps:
        - checkout
        - run:
            name: Build java
            no_output_timeout : 55m
            command: echo Hello, World!;python ox.py
  pytho:
    
    docker:
      - image: cimg/python:2.7
    steps:
      - checkout
      - run:
          name: Build python
          no_output_timeout : 55m
          command: echo Hello, World!;python ox.py
      
  vu:
      
      docker:
        - image: cimg/python:2.7
      steps:
        - checkout
        - run:
            name: Build vue
            no_output_timeout : 55m
            command: echo Hello, World!;python ox.py
  nod:
    
    docker:
      - image: cimg/python:2.7
    steps:
      - checkout
      - run:
          name: Build node
          no_output_timeout : 55m
          command: echo Hello, World!;python ox.py
      
  
        
        
workflows:
  version: 2.1
  create:
    jobs:
      - angular
      - angula   
      - java
      - jav
      - python
      - pytho  
      - vue
      - nod  
      - vu
      - node
          
